version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: java2-project-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/nginx/html:/etc/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/cert:/etc/nginx/cert
    privileged: true #必须要有，打开nginx文件调用权限
  backend:
    image: java2-project-backend
    container_name: java2-project-backend
    build: ./java
    ports:
      - "8443:8443"
