server:
  port: 8443

spring:
  datasource:
    url: jdbc:mysql://quanquancho.com:3306/java2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: quanquan
    password: wlqyanyalun008++

debug: true

mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: edu.sustech.backend.dto
